echo ""
echo "   Welcome to your Python Port Scanner Codespace!"
echo ""
echo "▶  To run the scanner, use:"
echo "    python src/port-scanner.py <target-ip> <port-range> <thread-count>"
echo "    e.g. python src/port-scanner.py 192.168.1.1 1-100 10"
echo ""
echo "    ⚠️Disclaimer:⚠️"
echo "    This tool is intended for educational and authorized use only."
echo "    Do not scan networks or devices you do not own or have permission to test."
echo "    Unauthorized use may be illegal. The author assumes no liability for misuse."
echo ""
